### ISSUE TITLE
general feedback

### ISSUE THREAD

**Issue by alexfreska** [mjmay08/SiaShare#1]
Hi, a few of us are excited to try this and gave the setup process a try. Here are a few issues we ran into:
- Scripts are only for dev mode
- Basic docs on running for prod
- Cannot turn off SSL as it still expects the files, ideally want a reverse proxy downstream (Caddy) to handle certs.
- File paths are hardcoded to windows (biggest blocker)
- Dockerfile would be great

Otherwise looking good! Hope this helps.

**Comment by mjmay08** [comment]
Hey @alexfreska, thanks for all of the feedback! I think I have addressed all of your issues, but I'm sure there is room for improvement. Give it another try and let me know how it goes.

- Added scripts for running in prod mode
- Added docs on how to run in prod mode (both with and without docker)
- Removed the requirement for having certificates allowing you to use a reverse proxy like Caddy
- Fixed hardcoded Windows file paths
- Added a Dockerfile
- Added a GitHub action to publish the docker image to make it easier for people to run without having to build themselves
