### ISSUE TITLE
Add bucket support

### ISSUE THREAD

**Issue by n8mgr** [mjmay08/SiaShare#7]
Add an optional bucket parameter to the config file so that uploaded files can be more organized

**Comment by mjmay08** [comment]
@n8maninger there is already a siaRootDir parameter and all files are stored under that directory :
![image](https://github.com/mjmay08/SiaShare/assets/7408476/a073a00c-4bb4-42cc-a75a-1bde0b2327bb)

Would adding a bucket parameter really be any different? Other than that the siashare directory wouldn't be underneath the default bucket.

**Comment by n8mgr** [comment]
It's a little different. Buckets provide a more clear boundary that folders don't.


![Screenshot 2023-12-29 at 10 44 29 AM](https://github.com/mjmay08/SiaShare/assets/5544150/ed03290f-0d27-4bd3-b69b-b320e2f2b6c2)
